//General
export const TOGGLE_MENU='TOGGLE_MENU';
export const SHOW_ALERT='SHOW_ALERT';
export const HIDE_ALERT='HIDE_ALERT';

//Activities
export const GET_ACTIVITIES_INIT = "GET_ACTIVITIES_INIT";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITIESS_ERROR = "GET_ACTIVITIESS_ERROR";
export const UPDATE_ACTIVITY_STATUS = "UPDATE_ACTIVITY_STATUS";
export const EDIT_ACTIVITY_SUCCESS = "EDIT_ACTIVITY_SUCCESS";
export const SHOW_EDIT_ACTIVITY = "SHOW_EDIT_ACTIVITY";

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR';


//Campaigns
export const GET_CAMPAIGNS_INIT = "GET_CAMPAIGNS_INIT";
export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS";
export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS";
export const GET_CAMPAIGNS_ERROR = "GET_CAMPAIGNS_ERROR";
export const UPDATE_CAMPAIGN_STATUS = "UPDATE_CAMPAIGN_STATUS";
export const EDIT_CAMPAIGN_SUCCESS = "EDIT_CAMPAIGN_SUCCESS";
export const SHOW_EDIT_CAMPAIGN = "SHOW_EDIT_CAMPAIGN";

export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const ADD_CAMPAIGN_SUCCESS = 'ADD_CAMPAIGN_SUCCESS';
export const ADD_CAMPAIGN_ERROR = 'ADD_CAMPAIGN_ERROR';


// Dialog

export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// Progress bar
export const SHOW_PROGRESS_BAR = "SHOW_PROGRESS_BAR";
export const HIDE_PROGRESS_BAR = "HIDE_PROGRESS_BAR";