//General
export const TOGGLE_MENU='TOGGLE_MENU';
export const SHOW_ALERT='SHOW_ALERT';
export const HIDE_ALERT='HIDE_ALERT';

//Activities
export const GET_ACTIVITIES_INIT = "GET_ACTIVITIES_INIT";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITIES_ERROR = "GET_ACTIVITIES_ERROR";
export const UPDATE_ACTIVITY_STATUS = "UPDATE_ACTIVITY_STATUS";
export const EDIT_ACTIVITY_SUCCESS = "EDIT_ACTIVITY_SUCCESS";
export const SHOW_EDIT_ACTIVITY = "SHOW_EDIT_ACTIVITY";

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR';

//Community
export const GET_USERS_INIT = "GET_USERS_INIT";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_COMMUNITY_INIT = "GET_COMMUNITY_INIT";
export const GET_COMMUNITY_SUCCESS = "GET_COMMUNITY_SUCCESS";
export const GET_COMMUNITY_ERROR = "GET_COMMUNITY_ERROR";

export const ADD_RELATION = 'ADD_RELATION';
export const ADD_RELATION_SUCCESS = 'ADD_RELATION_SUCCESS';
export const ADD_RELATION_ERROR = 'ADD_RELATION_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

// Dialog

export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// Progress bar
export const SHOW_PROGRESS_BAR = "SHOW_PROGRESS_BAR";
export const HIDE_PROGRESS_BAR = "HIDE_PROGRESS_BAR";